#!/bin/sh

if test -f .gitattributes && grep -q -F filter=lfs .gitattributes; then
  command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-commit' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
  exec git lfs post-commit "$@"
fi

if test -f .git/branchless/config; then
  command -v git-branchless >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for git-branchless but 'git-branchless' was not found on your path."; exit 2; }
  git branchless hook post-commit "$@"
fi
